const initialState = {
    
  adSoyadA:'', //düzeltme
  tcA:'',
  belgeNoA:'',
  alindigiYerA:'',
  adresA : '',
  cepTelA:'',
  sasiNoA: '',
  markaModelA : '',
  plakaA : '',
  kullanimSekliA : '',
  sigortalininAdSoyadA :'',
  tcVergiNoA : '',
  sigortaUnvanA : '',
  acenteNoA :'',
  tramerBelgeNoA : '',
  hizDurumuA : '',
  frenUzunluguA : '',
  yesilKartNoA : '',
  ulkeA : '',
  pasaportA : '',
  surucuGorusA : '',
  adSoyadB:'',
  tcB:'',
  belgeNoB :'',
  alindigiYerB :'',
  adresB : '',
  cepTelB :'',
  sasiNoB : '',
  markaModelB : '',
  plakaB : '',
  kullanimSekliB : '',
  sigortalininAdSoyadB :'',
  tcVergiNoB : '',
  sigortaUnvanB : '',
  acenteNoB :'',
  tramerBelgeNoB : '',
  hizDurumuB : '',
  frenUzunluguB : '',
  yesilKartNoB : '',
  ulkeB : '',
  pasaportB : '',
  surucuGorusB: '',

  kazaTarihi:'',
  kazaSaati :'',
  il : '',
  ilce : '',
  mahalle : '',
  cadde : '',
  semt : '',
  sokak : '',
  adSoyad : '',
  adres : '',
  telNo :'',


//değerleri gir

};
export default initialState;